<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLrexjU1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLrexjU1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLrexjU1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLrexjU1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLrexjU1\App_KernelDevDebugContainer([
    'container.build_hash' => 'LrexjU1',
    'container.build_id' => '726e54e7',
    'container.build_time' => 1653818884,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLrexjU1');
